# Set the build language to Python
language: python

python: 3.6

services:
  - mongodb
  - redis-server

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq ssdeep python-dev libfuzzy-dev
  - echo -e "[db]\nserver = 127.0.0.1\nport = 27017\ndb = Quark"| cat - > conf/db.conf
  - echo -e "[celery]\nsite = redis://@127.0.0.1:6379"| cat - > conf/celery.conf
  - echo -e "[gplay_api]\nlocale = en_US\ntimezone = UTC\ngoogle_password = PASS\ngoogle_login = USER"| cat - > conf/gplay_api.conf

# Install the codecov pip dependency
install:
  - pip install -r requirements.txt
  - pip install coveralls

# Run the unit test
script:
  - coverage run -m unittest discover 

after_success:
  - coveralls